### ISSUE TITLE
Version 1.3.9-e1 cannot run on MTR 4.0.0-beta10

### ISSUE THREAD

**Issue by DMB-codegang** [AIDA64S/MTR-Station-Decoration-Addon#17]
**Server Version**: 1.20.4 for Fabric 0.16.5  
**MSD Version**: 1.3.9-e1  
**MTR Version**: 4.0.0-beta-10  

**Error Log**:

```Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:32:05] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.16.5
[13:32:05] [main/WARN]: Mod resolution failed
[13:32:05] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE msd 1.3.9-e1 {depends mtr @ [>=4.0.0-beta-9]}, ROOT_FORCELOAD_SINGLE msd 1.3.9-e1]
[13:32:05] [main/INFO]: Reason: [HARD_DEP msd 1.3.9-e1 {depends mtr @ [>=4.0.0-beta-9]}]
[13:32:05] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, worldeditcui, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-models-v0, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
[13:32:05] [main/INFO]: Fix: add [], remove [], replace [[mtr 4.0.0-beta-10] -> add:mtr 4.0.0-beta-9 ([[4.0.0-beta-9,∞)])]
[13:32:05] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A possible solution has been identified, and applying it may solve your problem:
         - Replace mod 'Minecraft Transit Railway' (mtr) 4.0.0-beta-10 with version 4.0.0-beta-9 or higher.
More information:
         - Mod 'MTR Station Decoration Addon' (msd) 1.3.9-e1 requires 'Minecraft Transit Railway' (mtr) version 4.0.0-beta-9 or higher, but the installed version 4.0.0-beta-10 is not compatible!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.16.5-launcher.1.0.1.jar:1.0.1]```

**Comment by mrtajniak** [comment]
MSD 1.3.9-e1 cannot run on MTR B10

**Comment by Leven-mok** [comment]
i think this is bug of fabric likely

**Comment by CokeStudios** [comment]
fixed
